import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import PrelineScript from '@/widgets/preline/modal/PrelineScript'
import { Sidebar } from '@/shared/layout-components'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin']
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="ru" className="dark">
			<body className="bg-gray-50 dark:bg-neutral-900">
				{/* ========== HEADER ========== */}
				<header className="lg:ms-[260px] fixed top-0 inset-x-0 flex flex-wrap md:justify-start md:flex-nowrap z-50 bg-white border-b border-gray-200 dark:bg-neutral-800 dark:border-neutral-700">
					<div className="flex justify-between xl:grid xl:grid-cols-3 basis-full items-center w-full py-2.5 px-2 sm:px-5">
						<div className="xl:col-span-1 flex items-center md:gap-x-3">
							<div className="lg:hidden">
								{/* Sidebar Toggle */}
								<button
									type="button"
									className="w-7 h-[38px] inline-flex justify-center items-center gap-x-2 text-sm font-medium rounded-lg border border-gray-200 bg-white text-gray-800 shadow-sm hover:bg-gray-50 focus:outline-none focus:bg-gray-100 disabled:opacity-50 disabled:pointer-events-none dark:bg-neutral-800 dark:border-neutral-700 dark:text-neutral-300 dark:hover:bg-neutral-700 dark:focus:bg-neutral-700"
									aria-haspopup="dialog"
									aria-expanded="false"
									aria-controls="hs-pro-sidebar"
									aria-label="Toggle navigation"
									data-hs-overlay="#hs-pro-sidebar"
								>
									<svg
										className="shrink-0 size-4"
										xmlns="http://www.w3.org/2000/svg"
										width={24}
										height={24}
										viewBox="0 0 24 24"
										fill="none"
										stroke="currentColor"
										strokeWidth={2}
										strokeLinecap="round"
										strokeLinejoin="round"
									>
										<path d="M17 8L21 12L17 16M3 12H13M3 6H13M3 18H13" />
									</svg>
								</button>
								{/* End Sidebar Toggle */}
							</div>
						</div>
						<div className="xl:col-span-2 flex justify-end items-center gap-x-2">
							<div className="flex items-center"></div>

							<div className="border-e border-gray-200 w-px h-6 mx-1.5 dark:border-neutral-700" />
							<div className="h-[38px] ">
								{/* Account Dropdown */}
								<div className="hs-dropdown inline-flex   [--strategy:absolute] [--auto-close:inside] [--placement:bottom-right] relative text-start">
									<button
										id="hs-dnad"
										type="button"
										className="inline-flex shrink-0 items-center gap-x-3 text-start rounded-full focus:outline-none"
										aria-haspopup="menu"
										aria-expanded="false"
										aria-label="Dropdown"
									>
										<img
											className="shrink-0 size-[38px] rounded-full"
											src="https://images.unsplash.com/photo-1659482633369-9fe69af50bfb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=3&w=320&h=320&q=80"
											alt="Avatar"
										/>
									</button>
									{/* Account Dropdown */}
									<div
										className="hs-dropdown-menu hs-dropdown-open:opacity-100 w-60 transition-[opacity,margin] duration opacity-0 hidden z-20 bg-white rounded-xl shadow-[0_10px_40px_10px_rgba(0,0,0,0.08)] dark:shadow-[0_10px_40px_10px_rgba(0,0,0,0.2)] dark:bg-neutral-900"
										role="menu"
										aria-orientation="vertical"
										aria-labelledby="hs-dnad"
									>
										<div className="p-1 border-b border-gray-200 dark:border-neutral-800">
											<a
												className="py-2 px-3 flex items-center gap-x-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 disabled:opacity-50 disabled:pointer-events-none focus:outline-none focus:bg-gray-100 dark:text-neutral-300 dark:hover:bg-neutral-800 dark:focus:bg-neutral-800"
												href="../../pro/dashboard/user-profile-my-profile.html"
											>
												<img
													className="shrink-0 size-8 rounded-full"
													src="https://images.unsplash.com/photo-1659482633369-9fe69af50bfb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=3&w=320&h=320&q=80"
													alt="Avatar"
												/>
												<div className="grow">
													<span className="text-sm font-semibold text-gray-800 dark:text-neutral-300">
														James Collison
													</span>
													<p className="text-xs text-gray-500 dark:text-neutral-500">Preline@HS</p>
												</div>
											</a>
										</div>
										<div className="p-1">
											<a
												className="flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 disabled:opacity-50 disabled:pointer-events-none focus:outline-none focus:bg-gray-100 dark:text-neutral-300 dark:hover:bg-neutral-800 dark:focus:bg-neutral-800"
												href="#"
											>
												<svg
													className="shrink-0 mt-0.5 size-4"
													xmlns="http://www.w3.org/2000/svg"
													width={24}
													height={24}
													viewBox="0 0 24 24"
													fill="none"
													stroke="currentColor"
													strokeWidth={2}
													strokeLinecap="round"
													strokeLinejoin="round"
												>
													<rect width={20} height={14} x={2} y={5} rx={2} />
													<line x1={2} x2={22} y1={10} y2={10} />
												</svg>
												Billing
											</a>
											<a
												className="flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 disabled:opacity-50 disabled:pointer-events-none focus:outline-none focus:bg-gray-100 dark:text-neutral-300 dark:hover:bg-neutral-800 dark:focus:bg-neutral-800"
												href="#"
											>
												<svg
													className="shrink-0 size-4"
													xmlns="http://www.w3.org/2000/svg"
													width={24}
													height={24}
													viewBox="0 0 24 24"
													fill="none"
													stroke="currentColor"
													strokeWidth={2}
													strokeLinecap="round"
													strokeLinejoin="round"
												>
													<path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
													<circle cx={12} cy={12} r={3} />
												</svg>
												Settings
											</a>
											<a
												className="flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 disabled:opacity-50 disabled:pointer-events-none focus:outline-none focus:bg-gray-100 dark:text-neutral-300 dark:hover:bg-neutral-800 dark:focus:bg-neutral-800"
												href="#"
											>
												<svg
													className="shrink-0 mt-0.5 size-4"
													xmlns="http://www.w3.org/2000/svg"
													width={24}
													height={24}
													viewBox="0 0 24 24"
													fill="none"
													stroke="currentColor"
													strokeWidth={2}
													strokeLinecap="round"
													strokeLinejoin="round"
												>
													<path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
													<circle cx={12} cy={7} r={4} />
												</svg>
												My account
											</a>
										</div>
										<div className="px-4 py-3.5 border-y border-gray-200 dark:border-neutral-800">
											{/* Switch/Toggle */}
											<div className="flex justify-between items-center">
												<label
													htmlFor="hs-pro-dnaddm"
													className="text-sm text-gray-800 dark:text-neutral-300"
												>
													Dark mode
												</label>
												<div className="relative inline-block">
													<input
														data-hs-theme-switch
														type="checkbox"
														id="hs-pro-dnaddm"
														className="relative w-11 h-6 p-px bg-gray-100 border-transparent text-transparent rounded-full cursor-pointer transition-colors ease-in-out duration-200 focus:ring-blue-600 disabled:opacity-50 disabled:pointer-events-none checked:bg-none checked:text-blue-600 checked:border-blue-600 focus:checked:border-blue-600 dark:bg-neutral-800 dark:border-neutral-700 dark:checked:bg-blue-500 dark:checked:border-blue-500 dark:focus:ring-offset-neutral-900

              before:inline-block before:size-5 before:bg-white checked:before:bg-white before:translate-x-0 checked:before:translate-x-full before:rounded-full before:shadow before:transform before:ring-0 before:transition before:ease-in-out before:duration-200 dark:before:bg-neutral-400 dark:checked:before:bg-white"
													/>
												</div>
											</div>
											{/* End Switch/Toggle */}
										</div>
										<div className="p-1">
											<a
												className="flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 disabled:opacity-50 disabled:pointer-events-none focus:outline-none focus:bg-gray-100 dark:text-neutral-300 dark:hover:bg-neutral-800 dark:focus:bg-neutral-800"
												href="#"
											>
												Customization
												<div className="ms-auto">
													<span className="ms-auto inline-flex items-center gap-1.5 py-px px-1.5 rounded text-[10px] leading-4 font-medium bg-gray-100 text-gray-800 dark:bg-neutral-700 dark:text-neutral-300">
														New
													</span>
												</div>
											</a>
											<a
												className="flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 disabled:opacity-50 disabled:pointer-events-none focus:outline-none focus:bg-gray-100 dark:text-neutral-300 dark:hover:bg-neutral-800 dark:focus:bg-neutral-800"
												href="#"
											>
												Manage team
											</a>
											<a
												className="flex items-center gap-x-3 py-2 px-3 rounded-lg text-sm text-gray-800 hover:bg-gray-100 disabled:opacity-50 disabled:pointer-events-none focus:outline-none focus:bg-gray-100 dark:text-neutral-300 dark:hover:bg-neutral-800 dark:focus:bg-neutral-800"
												href="#"
											>
												Sign out
											</a>
										</div>
										<div className="p-1 border-t border-gray-200 dark:border-neutral-800">
											<button
												type="button"
												className="flex mt-0.5 gap-x-3 py-2 px-3 w-full rounded-lg text-sm text-gray-800 hover:bg-gray-100 disabled:opacity-50 disabled:pointer-events-none focus:outline-none focus:bg-gray-100 dark:text-neutral-300 dark:hover:bg-neutral-800 dark:focus:bg-neutral-800"
												data-hs-overlay="#hs-pro-dasadam"
												aria-expanded="false"
											>
												<svg
													className="shrink-0 size-4 mt-0.5"
													xmlns="http://www.w3.org/2000/svg"
													width={24}
													height={24}
													viewBox="0 0 24 24"
													fill="none"
													stroke="currentColor"
													strokeWidth={2}
													strokeLinecap="round"
													strokeLinejoin="round"
												>
													<circle cx={12} cy={12} r={10} />
													<path d="M8 12h8" />
													<path d="M12 8v8" />
												</svg>
												Add team account
											</button>
										</div>
									</div>
									{/* End Account Dropdown */}
								</div>
								{/* End Account Dropdown */}
							</div>
						</div>
					</div>
				</header>
				<Sidebar />
				{children}
				<PrelineScript />
			</body>
		</html>
	)
}
